prepare for v1.19.1
zowe/docs-site pull request #1566
Opened 2021-02-05 14:50 UTC by jackjia-ibm

Signed-off-by: Jack (T.) Jia <jack-tiefeng.jia@ibm.com>

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Please describe your pull request.

:heart:Thank you!

2021-02-05 14:59 UTC, OnnoVdT requested changes

2021-02-05 14:59 UTC, OnnoVdT commented on docs/getting-started/summaryofchanges.md
> +With the continuos optimization of Zowe build size, now Zowe release can fit in one PTF. This single PTF UO01969 will supersede PTF UO01967 and UO01968 from v1.19.0 release.
typo: continuos -> continuous

2021-02-05 14:59 UTC, OnnoVdT commented on docs/getting-started/summaryofchanges.md
> +Fixed missing HOLD data about extra steps the system programmer should take after applying the PTF. It explains new configurations we introduced in `instance.env` and also a reconfiguration step with
new configurations -> new configuration options

2021-02-05 14:59 UTC, OnnoVdT commented on docs/README.md
> +**[V1.19.x](https://docs.zowe.org/stable/Zowe_Documentation.pdf)** |
is it indeed v1.19.x ? other places you always specify 1.19.1

2021-02-05 15:57 UTC, OnnoVdT approved these changes

2021-02-08 08:21 UTC, nannanli commented
@jackjia-ibm Thank you for the updates! I just made very minor tweaks. It looks good to me now so feel free to merge it when 1.19.1 is published.

2021-02-08 08:21 UTC, nannanli approved these changes

2021-02-11 21:48 UTC, merged