Update cli-using-daemon-mode.md
zowe/docs-site pull request #1882
Opened 2021-11-02 15:17 UTC by aimmta

Signed-off-by: Michael Aimino <michael.aimino@broadcom.com>

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
- [x] Cleanup documentation that may be referencing "zowex"

- [x] Cleanup documentation that may be referencing daemon startup commands

- [ ] Publish new @next version of Zowe CLI to public npm and binary executables to GitHub

https://rally1.rallydev.com/#/227079578160ud/teamplan?detail=%2Fuserstory%2F613392093263

2021-11-03 14:24 UTC, gejohnston requested changes
The behavior of the zowe executable has been changed, so the section titled "Starting Zowe in daemon mode" must be rewritten. I suggest the following:

Running zowe commands with the zowe executable

Verify that you have installed the @next release of Zowe CLI and the zowe native executable.

Run any zowe command as you normally would. The first time you run any zowe command, the command will automatically start a daemon in the background. It will then run your desired command. Since that first command must start the daemon, that first zowe command will actually run slower than a traditional zowe command. However, every zowe command afterward will run significantly faster. The daemon will continue to run in the background until you close your terminal window.

Example:
```
    zowe --version
    Starting a background process to increase performance ...
    7.0.0-next.202110211759

    zowe --version
    7.0.0-next.202110211759
```

2021-11-03 18:03 UTC, zFernand0 reviewed
Added some comments in regards to the unidentified GitHub developer warning for Mac Users 😋

2021-11-03 18:03 UTC, zFernand0 commented on docs/user-guide/cli-using-daemon-mode.md
> +4. Unzip the zowe .tgz file and place the zowe (or zowe.exe) file into a directory which occurs on your PATH earlier than the directory containing the NodeJS zowe command.
I'd like to add a note (for Mac Users) alongside these steps to indicate that people may (or may not) need to accept GitHub as an unidentified developer.
More details (and link with steps) can be found in the issue:
- https://github.com/zowe/zowe-cli/issues/1193

2021-11-04 15:02 UTC, aimmta commented on docs/user-guide/cli-using-daemon-mode.md
> +You can download and install the zowe native executable from Zowe Downloads (preferred) or from the Zowe Github repository. To install the zowe native executable from Zowe Downloads, see [Install Zow
Should I hold off on making further changes until these issues are completed?

2021-11-04 15:55 UTC, zFernand0 commented on docs/user-guide/cli-using-daemon-mode.md
> +You can download and install the zowe native executable from Zowe Downloads (preferred) or from the Zowe Github repository. To install the zowe native executable from Zowe Downloads, see [Install Zow
For now, we can hold off on documentation updates related to the `zowe config daemon` command until the two issues above are completed.
However, we should still add the Mac-only note regarding the unidentified developer issue (next comment - https://github.com/zowe/docs-site/pull/1882#discussion_r742204064)

2021-11-08 19:31 UTC, gejohnston approved these changes
While I believe that Fernando has some additional updates, I approve the changes that I requested.

2021-11-09 18:26 UTC, aimmta commented
Added the note for Mac users. Going to merge this PR and address the changes for zowe/zowe-cli#1175
zowe/zowe-cli#1176 when those are ready.

2021-11-09 18:26 UTC, merged