story US785459 [next] Validate @zowe/cli@next installation works on z/OS USS and zLinux
zowe/docs-site pull request #2029
Opened 2022-02-11 20:43 UTC by JamesBauman

Please review:

https://github.com/zowe/docs-site/blob/jabauman-USS-zLinux/docs/user-guide/cli-install-cli-next.md
https://github.com/zowe/docs-site/blob/jabauman-USS-zLinux/docs/user-guide/cli-using-daemon-mode.md
https://github.com/zowe/docs-site/blob/jabauman-USS-zLinux/docs/user-guide/cli-configure-daemon-on-zlinux-os.md
https://github.com/zowe/docs-site/blob/jabauman-USS-zLinux/docs/user-guide/cli-configure-scs-on-zlinux-os.md
https://github.com/zowe/docs-site/blob/jabauman-USS-zLinux/docs/user-guide/cli-configure-os-where-scs-unavailable.md

thx,

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Please describe your pull request.

:heart:Thank you!

2022-02-15 16:06 UTC, awharn approved these changes
These changes look good to me. The `Configure daemon mode on z/Linux operating systems` section's list under step 3 has a bit of an odd spacing, but I don't see anything wrong in the markdown to cause that, aside from perhaps an extra line.

2022-02-15 16:24 UTC, JamesBauman commented
@MikeBauerCA   pending your review.   

FYI that we added three articles to the doc site;  They are highlighted below

![image](https://user-images.githubusercontent.com/36677566/154104389-b8416464-c6c7-4de8-b6a6-777e8919d3b4.png)


thx

2022-02-16 18:15 UTC, MikeBauerCA requested changes

2022-02-16 18:15 UTC, MikeBauerCA commented on docs/user-guide/cli-install-cli-next.md
> +   2. Follow the steps in follow the steps in [Install Zowe CLI from npm](install-zowe-cli-from-npm) or [Install Zowe CLI from a download](#install-zowe-cli-from-a-download).
"Follow the steps in" is written twice

2022-02-16 18:15 UTC, MikeBauerCA commented on docs/user-guide/cli-install-cli-next.md
> +   1. Follow the steps in follow the steps in [Install Zowe CLI from npm](install-zowe-cli-from-npm) or [Install Zowe CLI from a download](#install-zowe-cli-from-a-download).
"Follow the steps in" is written twice

2022-02-16 18:54 UTC, awharn commented on docs/user-guide/cli-configure-scs-on-zlinux-os.md
> +    **Note:** The z/Linux system where you are configuring SCS might require internet access to install the packages.
That makes sense. In this case, internet access will be required if you are using the Red Hat package repository. 

Some sites might host their own package repositories, but those repositories might not have all of the packages we require. In that case, someone will need to either add the required package(s) to that repository (I have no idea how you would go about doing that), or need internet access to use Red Hat's.

2022-02-16 20:21 UTC, JamesBauman commented on docs/user-guide/cli-configure-os-where-scs-unavailable.md
> +# Configure operating systems where the Secure Credential Store is not available
done

2022-02-16 20:21 UTC, JamesBauman commented on docs/user-guide/cli-configure-os-where-scs-unavailable.md
> +Team configuration can be created without access to the Secure Credential Store. However, team configuration does not store sensitive user information on the system. Subsequent commands prompt for th
done

2022-02-16 20:21 UTC, JamesBauman commented on docs/user-guide/cli-configure-scs-on-zlinux-os.md
> +    **Note:** The z/Linux system where you are configuring SCS might require internet access to install the packages.
done, please review.....

2022-02-16 20:21 UTC, JamesBauman commented on docs/user-guide/cli-configure-scs-on-zlinux-os.md
> +    - **#**: Replace # with the major version of RHEL that is running on the z/Linux system.
done

2022-02-16 20:22 UTC, JamesBauman commented on docs/user-guide/cli-configure-scs-on-zlinux-os.md
> +5. Install the Red Hat Developer Toolset to ensure that you are running version of the gcc-c++ compiler that can build the SCS native binaries.
doh!  

done

2022-02-16 20:22 UTC, JamesBauman commented on docs/user-guide/cli-install-cli-next.md
> +   2. Follow the steps in follow the steps in [Install Zowe CLI from npm](install-zowe-cli-from-npm) or [Install Zowe CLI from a download](#install-zowe-cli-from-a-download).
doh!
doh!
doh!

Done-done-done...

2022-02-16 20:22 UTC, JamesBauman commented on docs/user-guide/cli-install-cli-next.md
> +   1. Follow the steps in follow the steps in [Install Zowe CLI from npm](install-zowe-cli-from-npm) or [Install Zowe CLI from a download](#install-zowe-cli-from-a-download).
done

2022-02-16 20:25 UTC, JamesBauman commented on docs/user-guide/cli-configure-scs-on-zlinux-os.md
> +    **Note:** The z/Linux system where you are configuring SCS might require internet access to install the packages.
@awharn and @MikeBauerCA 

Please review the words the I used for this change/

2022-02-16 20:29 UTC, JamesBauman commented
note the following URL change (changed topic title)
**From**
https://github.com/zowe/docs-site/blob/jabauman-USS-zLinux/docs/user-guide/cli-configure-os-where-scs-unavailable.md
**To**
https://github.com/zowe/docs-site/blob/jabauman-USS-zLinux/docs/user-guide/cli-configure-cli-on-os-where-scs-unavailable.md

2022-02-17 16:01 UTC, awharn requested changes
I think there is just one small change that needs to be made.

2022-02-17 16:01 UTC, awharn commented on docs/user-guide/cli-configure-scs-on-zlinux-os.md
> +    **Note:** If you are installing the Linux packages on a RHEL system, the system where you are configuring SCS might require Internet access. When a site hosts its own package repositories, the re
This isn't specific to a RHEL system, if you are installing Linux packages, any system might require internet access.

2022-02-17 17:12 UTC, JamesBauman commented on docs/user-guide/cli-configure-os-where-scs-unavailable.md
> +# Configure operating systems where the Secure Credential Store is not available
This was updated as requested...


https://github.com/zowe/docs-site/blob/jabauman-USS-zLinux/docs/user-guide/cli-configure-cli-on-os-where-scs-unavailable.md

Dismissing the review

2022-02-17 17:34 UTC, MikeBauerCA approved these changes

2022-02-17 17:47 UTC, JamesBauman commented
Signed-off-by: JamesBauman <james.bauman@broadcom.com>

2022-02-17 18:07 UTC, merged