Zowe chat docs
zowe/docs-site pull request #2451
Opened 2022-10-25 19:13 UTC by nannanli

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Please describe your pull request.

:heart:Thank you!

2022-10-26 06:03 UTC, XuehongBJLiang commented on docs/troubleshoot/zowe-chat-troubleshoot/troubleshooting.md
> +When you run into some errors, you can check the server log which can be found in `$ZOWE_CHAT_HOME/chatServer.log/`.
Hi. log directory is $ZOWE_CHAT_HOME/log and log file is $ZOWE_CHAT_HOME/log/chatServer.log

2022-10-26 09:24 UTC, samanthasusu requested changes

2022-10-26 09:24 UTC, samanthasusu commented on docs/user-guide/zowe-chat/systemrequirements-chat.md
> +     See [Configuring Mattermost chat platform](chat_prerequisite_mattermost.md).
The links have some issues with urlencoder

2022-10-26 09:24 UTC, samanthasusu commented on docs/user-guide/zowe-chat/chat_configure_teams.md
> +   # The password will be encrypted automatically by Z ChatOps server with <AES> prefix added.
delete

2022-10-26 09:24 UTC, samanthasusu commented on docs/user-guide/zowe-chat/chat_configure_mattermost.md
> +   # The token will be encrypted automatically by Z ChatOps server with <AES> prefix added.
delete

2022-10-26 09:24 UTC, samanthasusu commented on docs/user-guide/zowe-chat/systemrequirements-chat.md
> +   To configure the port number for Microservice, edit the Microservice server configuration file<!--at ZCHATOPS_HOME/microservice/config/bnzsvc-server.yaml-->.
microservice -> web app
Path: “zchatops”

2022-10-31 11:17 UTC, samanthasusu approved these changes
LGTM! Thanks

2022-10-31 11:27 UTC, merged