Add ZWES0054E to error msg
zowe/docs-site pull request #2875
Opened 2023-05-17 07:26 UTC by samanthasusu

Signed-off-by: samanthasusu <Wen.Ting.Su@ibm.com>
- Add the ZWES0054E which was not documented before.

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../docs/contribute/contributing.md) to this repository.

- [ ] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 
      
- [ ] If this PR relates to GitHub issues in `docs-site` or other repositories, please list in Description, prefixed with **close**, **fix** or **resolve** keywords.

### Description (including links to related git issues)
Please describe your pull request.
fix #2873 
:heart:Thank you!

2023-08-31 03:28 UTC, samanthasusu commented
@1000TurquoisePogs hi Sean, would you please review this tip and see if it can be merged into doc? Thank you!

2024-03-27 15:15 UTC, samanthasusu commented
I suggest we add this error message to the troubleshooting section as I just find that it is not available on the live site yet. Would you mind taking this PR over to get it merged Andrew @janan07 ? Thanks!

2024-04-03 13:08 UTC, 1000TurquoisePogs requested changes

2024-04-03 13:08 UTC, 1000TurquoisePogs commented on docs/troubleshoot/app-framework/zss-error-codes.md
> +  The `IZPSRGSP`,`IZPSRGAD`, and `ZWESVUSR` need read access to the profile `OMVSAPPL`. Then the ZWESASTC started task was started successfully by the ZWESISTS started task.
IZP is some third party thing, not part of Zowe.
And `ZWESVUSR` is just the default name of Zowe's user account.

This should read as:

> When the Zowe STC userid has read access to the profile SAF `OMVSAPPL`, the ZWESASTC task will be able to successfully be started on an as-needed basis from ZWESISTC.

2024-04-03 13:08 UTC, 1000TurquoisePogs commented on docs/troubleshoot/app-framework/zss-error-codes.md
> +  authPluginLib was missing in the `ZWESASTC JCL` and the `ZWESISTS JCL`.
ZWESISTC, not ZWESISTS

2024-08-15 16:57 UTC, 1000TurquoisePogs approved these changes

2024-08-15 16:57 UTC, merged