Zowe Server Install Wizard
zowe/docs-site pull request #3663
Opened 2024-05-14 12:17 UTC by lparadkar-rocket

Please take a look at both the versions and provide suggestions.

Describe your pull request here:
Working on Zowe Server Install Wizard with Andrew.

List the file(s) included in this PR:
test-zen-doc.md
test-zen-doc_Sean.md

After creating the PR, follow the instructions in the comments.

2024-06-04 14:32 UTC, 1000TurquoisePogs approved these changes
I think it looks good, but here's my wishlist for further improvements:

1) SMPE or PAX pages of the existing documentation don't talk about the install wizard yet do they? Can we shout it out briefly in those sections so that people are aware of their options?

2) I wish I had a better suggestion, but its still a little strange to me that we have "Installing via SMPE" and "Installing via PAX" but the install wizard section in the sidebar isnt "Installing via..." it's just "overview".

2024-06-25 14:48 UTC, DivergentEuropeans requested changes

2024-06-25 14:48 UTC, DivergentEuropeans commented on docs/user-guide/install-zowe-server-install-wizard.md
> +- Inputs to the prompts are validated, so that invalid input or typos entered in any commands are prevented.
entered in most commands*

2024-06-25 14:48 UTC, DivergentEuropeans commented on docs/user-guide/install-zowe-server-install-wizard.md
> +3. Select Use FTP over TLS (Highly Recommended). Provide details as described in the following table:
Select "Use FTP with TLS." (reword)

2024-06-25 14:48 UTC, DivergentEuropeans commented on docs/user-guide/install-zowe-server-install-wizard.md
> +4. Select **Accept all certificates**.
Wrong. It is not recommended to select "Accept all certificates". Selecting "Accept all certificates" will disable certificate verificiation

2024-06-25 14:48 UTC, DivergentEuropeans commented on docs/user-guide/install-zowe-server-install-wizard.md
> +8. In the **Job statement** field, customize the job statement if needed and click **SAVE AND VALIDATE**.
*customize the job statement (or use default)

2024-06-25 14:48 UTC, DivergentEuropeans commented on docs/user-guide/install-zowe-server-install-wizard.md
> +9. In the **Planning window**, provide details for z/OS Unix locations, identifiers, and z/OSMF details.
*provide details for z/OS Unix locations (including Node and Java), identifiers, and z/OSMF details.

*Further down the page, provide [...]

2024-06-25 14:48 UTC, DivergentEuropeans commented on docs/user-guide/install-zowe-server-install-wizard.md
> +    </details>
Then --> Continue to "Unpax"
Then --> "Begin Download"

Then wait for statuses to finish. After they finish, move onto Step 2

2024-07-02 14:12 UTC, 1000TurquoisePogs commented on docs/user-guide/install-zowe-server-install-wizard.md
> +|STC (NYI)|**Purpose**:<br /> ZWESLSTC is the job for running Zowe's webservers. ZWESISTC runs the APF authorized cross-memory server. The ZWESASTC job is started by ZWESISTC on an as-needed basis.<b
This is no longer (NYI).
It's implemented.

2024-07-06 18:43 UTC, DivergentEuropeans approved these changes
Looks pretty good now

2024-07-06 18:48 UTC, DivergentEuropeans commented on docs/user-guide/install-zowe-server-install-wizard.md
> +If you are still unsure how to proceed, make a backup of these log files, and then use the following procedure to remove the Wizard's cache.
"If you are still unsure how to proceed, make a backup of these log files, and then use the following procedure to remove the Wizard's cache." -->

"If you are still unsure how to proceed, (optional) make a backup of these log files, and then use the following procedure to remove the Wizard's cache."

2024-07-08 15:22 UTC, janan07 approved these changes
I did a bit more refactoring to bring this up to our Zowe doc standards. I think it's in good condition to publish.

2024-07-23 14:11 UTC, merged