V3 API Mediation Layer related cleanup
zowe/docs-site pull request #3777
Opened 2024-07-22 08:27 UTC by balhar-jakub

Describe your pull request here:
I went through the API ML related doc for V3 and cleansed pieces that aren't relevant for V3 or claim information such as supported from specific Zowe version. 

List the file(s) included in this PR:

After creating the PR, follow the instructions in the comments.

2024-07-22 15:32 UTC, anaxceron requested changes
Looks pretty good @balhar-jakub. Made some comments that should be addressed.

2024-07-22 15:32 UTC, anaxceron commented on docs/appendix/zowe-yaml-configuration.md
> +  Specifies the SAF registry used to group the identities recognized as having a OIDC identity mapping. The registry name is the string used during the creation of the mapping between the dustributed
should be "... **an** OIDC ..."

2024-07-22 15:32 UTC, anaxceron commented on docs/appendix/zowe-yaml-configuration.md
> +  **Note:** User authorization is required to use the `IRR.RUSERMAP` resource within the `FACILITY` class. The default value is `ZWESVUSR`. Permissions are set up during installation with the `ZWESEC
Please use the Docusaurus admonition syntax:
https://docusaurus.io/docs/next/markdown-features/admonitions

2024-07-22 15:32 UTC, anaxceron commented on docs/appendix/zowe-yaml-configuration.md
> +  This property specifies the list of cluster nodes (members). In case of multiple instances, the value for each Caching Service instance can be either a list of all the members, separated by a comma
The phrase "either a list of all the members, separated by a comma ... " is repeated twice in this definition. It looks like a copy/paste error. Can you confirm?

2024-07-22 15:32 UTC, anaxceron commented on docs/appendix/zowe-yaml-configuration.md
> +  The default value is `data`. If you run the Caching Service in HA and the instances use the same filesystem, you have to specify a different value of the `CACHING_STORAGE_INFINISPAN_PERSISTENCE_DAT
We should spell out "HA."

2024-07-22 15:32 UTC, anaxceron commented on docs/appendix/zowe-yaml-configuration.md
> +  The port number used by Infinispan to synchronise data among cahing-service instances.
typo on "cahing-service"

2024-07-22 15:32 UTC, anaxceron commented on docs/getting-started/overview.md
> +to discover more about adding new APIs to the API Mediation Layer and using the API Catalog:
Please change "discover" to "learn." "Discover" sounds a little awkward in this particular use.

2024-07-22 15:32 UTC, anaxceron commented on docs/getting-started/zowe-security-overview.md
> +For testing purposes of Zowe, it is acceptable to use certificates issued and signed either by the company's local CA, or even certificates issued by Zowe security tools and signed by generated CA sp
- Please use the Docusaurus syntax for admonitions. See previous statement for the URL.
- We should spell out "CA" on first use.

2024-07-22 15:32 UTC, anaxceron commented on docs/troubleshoot/troubleshoot-apiml.md
> +The hostname that is displayed in the details of the exception is a valid hostname. You can validate that the hostname is valid by using `ping` command on the same mainframe system. For example, `pin
"that is not allowed to **do** network access" sounds awkward. can we change it to "that is not allowed network access"?

2024-07-22 15:32 UTC, anaxceron commented on docs/contribute/guidelines-code/categories.md
> +- **API Mediation Layer** - Java, Spring, JavaScript
Please use the Docusaurus admonition syntax:
https://docusaurus.io/docs/next/markdown-features/admonitions

2024-07-23 09:18 UTC, balhar-jakub commented
@anaxceron Resolved all the comments.

2024-07-23 12:37 UTC, anaxceron approved these changes

2024-07-23 12:53 UTC, t1m0thyj commented on docs/user-guide/api-mediation/api-mediation-caching-service.md
> +- {Development Use Only} Using InMemory
In Docusaurus V3, curly braces need to be escaped:
```suggestion
- \{Deprecated\} Using VSAM
- \{Development Use Only\} Using InMemory
```

Escaping them should fix the build error 🙏 
![image](https://github.com/user-attachments/assets/0b152517-0b4d-4308-ae97-dd4b6edf5216)

2024-07-24 08:28 UTC, merged