doc for profile config for mult API ML instances
zowe/docs-site pull request #3815
Opened 2024-08-15 19:00 UTC by anaxceron

Describe your pull request here: Doc for profile config for multiple API ML instances

List the file(s) included in this PR: cli-using-creating-profiles.md, ze-profiles.md

After creating the PR, follow the instructions in the comments.

2024-08-15 19:47 UTC, adam-wolfe requested changes

2024-08-15 19:47 UTC, adam-wolfe commented on docs/user-guide/cli-using-creating-profiles.md
> +## Accessing services for multiple API ML instances
I would say "Accessing services through multiple API ML gateways"

2024-08-15 19:47 UTC, adam-wolfe commented on docs/user-guide/cli-using-creating-profiles.md
> +In the following configuration, the profiles are structured to allow multiple instances of the API ML.
"... structured to connect to services using multiple API ML gateways."

2024-08-15 19:47 UTC, adam-wolfe commented on docs/user-guide/ze-profiles.md
> +1. Right-click on a profile on one of the ZE trees, the profiles you want to connect through with the api ml
"api ml" should be upper-case

2024-08-15 19:47 UTC, adam-wolfe commented on docs/user-guide/ze-profiles.md
> +4. In the next quick pick, select the appropriate option for authenticating to the API ML (user/pw or a cert file)
Not sure that we normally abbreviate password like this.

2024-08-15 19:47 UTC, adam-wolfe commented on docs/user-guide/ze-profiles.md
> +5. Enter the into prompted for (credentials, or browsing to the certificate file)
"into" should be "info". Something is weird about the wording/verb tense in this line.

2024-08-16 13:56 UTC, t1m0thyj reviewed
Thanks @anaxceron! I agree with Adam's comments and left a few more 😁

2024-08-16 13:56 UTC, t1m0thyj commented on docs/user-guide/ze-profiles.md
> +Before you log in and connect your service profile, ensure that you have [Zowe CLI](../user-guide/cli-install-cli-checklist.md) v6.16 or higher installed.
I think this line could be removed - since the Zowe CLI version shipped with Zowe V2/V3 is v7 or newer it already meets this criteria.

2024-08-16 13:56 UTC, t1m0thyj commented on docs/user-guide/ze-profiles.md
> +3. In the quick pick, select Log in to Authentication Service
Should UI labels ("Manage Profile", "Log in to Authentication Service") be bolded like they are in the Log-out section below?

2024-08-16 13:56 UTC, t1m0thyj commented on docs/user-guide/ze-profiles.md
> +Review [Accessing services for multiple API ML instances](../user-guide/cli-using-creating-profiles.md#accessing-services-for-multiple-api-ml-instances) to see how profiles are structured in the conf
Would it make sense to turn this section into a note, and move it higher in the article so readers would see it before they follow the log-in/log-out steps?

> [!NOTE]  
> If you want to access services thru multiple API ML gateways, the same steps apply, but you must first edit your configuration file to follow a specific structure.
> Review [Accessing services for multiple API ML instances](../user-guide/cli-using-creating-profiles.md#accessing-services-for-multiple-api-ml-instances) to see how profiles are structured in the configuration file.

2024-08-16 17:38 UTC, sbohnert approved these changes
Looks good. Thanks

2024-08-27 17:51 UTC, adam-wolfe commented on docs/user-guide/cli-using-creating-profiles.md
> +In the following configuration, the profiles are structured to allow multiple instances of the API ML.
I would also suggest adding a small note along the lines of:
"To authenticate to a specific API ML gateway from this config, you can run `zowe auth login apiml --base-profile lpar1` or `zowe auth login apiml --base-profile lpar2`.

Question for @t1m0thyj, would it make sense (or be more confusing) to have one of the `lpar` profiles set as the default base profile in this sample config?.

2024-08-28 19:38 UTC, adam-wolfe commented on docs/user-guide/ze-profiles.md
> +:::note
We should remove this note since it is no longer correct.

2024-09-06 18:47 UTC, adam-wolfe approved these changes
LGTM, thanks @anaxceron

2024-09-10 15:56 UTC, merged