Fix webui and misc docs for v3
zowe/docs-site pull request #3918
Opened 2024-10-03 19:50 UTC by 1000TurquoisePogs

This PR builds upon #3917 to fix branch sync issues. While doing review I also fixed a reference for JWT and a header.

2024-10-04 13:03 UTC, janan07 approved these changes

2024-10-04 13:19 UTC, zFernand0 requested changes
Requesting changes not because this PR is bad, but to prevent it from being merged for now.

I found a commit that technically contains all of the changes that need to be reverted which I missed on my PR.

Thanks for opening this PR as it helped me pinpoint which commit I missed.

2024-10-04 14:14 UTC, janan07 approved these changes

2024-10-08 15:18 UTC, zFernand0 approved these changes

2024-10-08 15:30 UTC, anaxceron approved these changes

2024-10-08 19:34 UTC, merged