Updated advanced configuration for app framework page for v3
zowe/docs-site pull request #3939
Opened 2024-10-09 20:01 UTC by 1000TurquoisePogs

The page "[Configuring Zowe Application Framework](https://docs.zowe.org/stable/user-guide/mvd-configuration)" (mvd-configuration.md) is currently accurate for v3, but just overall dated.

There are things in here that don't need to be said for v3, or can be said more simply because documentation elsewhere has been created and refined (AT-TLS documentation, MFA, how to access)

There are things here (v1 environment variable compatibility and HTTP mode) that I do not want documented because there is no reason why anyone should do that these days.

And finally, the name in the sidebar and the similar APIML page do not match a naming scheme.
<img width="272" alt="image" src="https://github.com/user-attachments/assets/b450a9f0-eee8-4447-81a9-7488bddc3fa4">

I have updated this page's title to match APIML's so that there is some consistency.

2024-10-10 09:52 UTC, janan07 commented on docs/user-guide/mvd-configuration.md
> -The app-server uses the Zowe server configuration file for customizing server behavior. For a full list of parameters, requirements, and descriptions, see [the json-schema document for the app-server
Multiple links are not found with these changes. Please see the broken links report.

2024-10-10 09:53 UTC, janan07 requested changes
Please see the broken links report for broken links introduced in this PR

2024-10-11 13:16 UTC, 1000TurquoisePogs commented
I think this PR's content could be ready to go, but I'm just awaiting review from more webui members to see if they have other feedback.

2024-10-11 14:39 UTC, janan07 approved these changes

2024-10-11 14:39 UTC, janan07 commented
The link checker test now passes.

2024-10-14 09:56 UTC, janan07 commented
Broken links have been fixed

2024-10-22 21:03 UTC, merged